name: detectron2
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - torchvision
  - numpy
  - pip:
      - detectron2 @ git+https://github.com/facebookresearch/detectron2@v0.7
      - opencv-python
      - tqdm
